# Generated by Django 5.1.2 on 2025-01-19 02:44

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0023_alter_applyuser_managers_applyuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyuser',
            name='username_of_telegram',
            field=models.CharField(default='3f852cc8-595b-4ffd-b4e2-5611d58fc0f1', max_length=255, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='applyuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
